apiVersion: v1
kind: Pod
metadata:
  name: inventory
spec:
  containers:
  - name: inventory
    image: wst24365888/tsmc-careerhack-2023-c6-inventory-service
    ports:
    - containerPort: 8200
      hostPort: {{ .Values.app.inventory.hostPort }}
  tolerations:
      - key: "app"
        operator: "Equal"
        value: "inventory"
        effect: "NoSchedule"