apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres
      args:
      - -c
      - max_connections=1000
      - -c
      - shared_buffers=1024MB
      image: postgres:15.1
      ports:
        - containerPort: 5432
          hostPort: {{ .Values.app.postgres.hostPort }}
      env:
        - name: POSTGRES_DB
          value: careerhack
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: tsmchackathon
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: "mendix-pgdata"
  volumes:
    - hostPath:
        path: "/root/db"
      name: mendix-pgdata
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"
